services:
  - type: web
    name: atlas-site
    runtime: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      cd ../frontend
      npm install --legacy-peer-deps
      npm run build
      rm -rf ../backend/static
      cp -r build ../backend/static
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: TON_RECEIVER_ADDRESS
        value: UQAzeFO819-pumlHDacrkiD_FmepkupojDj7OPTPDHe3hH2j
      - key: TON_PRICE_USD
        value: "28.99"
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PIN
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
